name: Post Release
on:
  release:
    types: [ published ]
jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup vars
        id: vars
        env:
          RELEASE_REF: ${{ github.ref }}
        run: echo "::set-output name=tag::${RELEASE_REF#refs/tags/}"

      - name: Download release content
        run: |
          echo "https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/modern.tar.gz"
          wget -O modern.tar.gz "https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/modern.tar.gz"
          mkdir ./dist
          tar zxf modern.tar.gz -C ./dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker and push (on modern)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            ix64/unlock-music:latest
            ix64/unlock-music:${{ steps.vars.outputs.tag }}

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup vars
        id: vars
        env:
          RELEASE_REF: ${{ github.ref }}
        run: echo "::set-output name=tag::${RELEASE_REF#refs/tags/}"

      - name: Download release content
        run: |
          echo "https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/modern.tar.gz"
          wget -O modern.tar.gz "https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/modern.tar.gz"
          mkdir ./dist
          tar zxf modern.tar.gz -C ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

